### ISSUE TITLE
Überschrift Hintergrund Farbe

### ISSUE THREAD

**Issue by s0krates** [pc-coholic/IHDB#7]
Die Farbe der Überschrift Hintergrund Farbe vielleicht in einem weichem grau damit man sieht das, dass eine Überschrift ist.

**Comment by pc-coholic** [comment]
Keine Lust gehabt das CSS anzupassen - jetzt ist es Kontextsensitiv rot (wichtige Einträge) bzw. blau (der ganze Rest9
